EOF space

diff --git a/.github/workflow/trufflehog.yml b/.github/workflow/trufflehog.yml
--- a/.github/workflow/trufflehog.yml
+++ b/.github/workflow/trufflehog.yml
@@ -68,4 +68,4 @@ jobs:
 
       - name: Scan Results Status
         if: steps.trufflehog.outcome == 'failure'
-        run: exit 1  # Set workflow run to failure if TruffleHog finds secrets 
+        run: exit 1  # Set workflow run to failure if TruffleHog finds secrets
